export const todaysProduct = [
  {
    id: 0,
    name: "HAVIT HV-G92 Gamepad",
    price: 100,
    discount: 50,
    image: "/img/today_1.png",
  },
  {
    id: 1,
    name: "AK-900 Wired Keyboard",
    price: 200,
    discount: 25,
    image: "/img/today_2.png",
  },
  {
    id: 2,
    name: "IPS LCD Gaming Monitor",
    price: 300,
    discount: 90,
    image: "/img/today_3.png",
  },
  {
    id: 3,
    name: "S-Series Comfort Chair",
    price: 400,
    discount: 15,
    image: "/img/today_4.png",
  },
  {
    id: 4,
    name: "AK-900 Wired Keyboard",
    price: 500,
    discount: 80,
    image: "/img/today_2.png",
  },
  {
    id: 5,
    name: "IPS LCD Gaming Monitor",
    price: 600,
    discount: 35,
    image: "/img/today_3.png",
  },
  {
    id: 6,
    name: "HAVIT HV-G92 Gamepad",
    price: 700,
    discount: 40,
    image: "/img/today_1.png",
  },
  {
    id: 7,
    name: "AK-900 Wired Keyboard",
    price: 800,
    discount: 45,
    image: "/img/today_2.png",
  },
  {
    id: 8,
    name: "S-Series Comfort Chair",
    price: 900,
    discount: 50,
    image: "/img/today_4.png",
  },
  {
    id: 9,
    name: "HAVIT HV-G92 Gamepad",
    price: 1100,
    discount: 60,
    image: "/img/today_1.png",
  },
  {
    id: 10,
    name: "IPS LCD Gaming Monitor",
    price: 1200,
    discount: 65,
    image: "/img/today_3.png",
  },
  {
    id: 11,
    name: "AK-900 Wired Keyboard",
    price: 300,
    discount: 70,
    image: "/img/today_2.png",
  },
  {
    id: 12,
    name: "  HAVIT HV-G92 Gamepad",
    price: 400,
    discount: 75,
    image: "/img/today_1.png",
  },
  {
    id: 13,
    name: "IPS LCD Gaming Monitor",
    price: 500,
    discount: 80,
    image: "/img/today_2.png",
  },
  {
    id: 14,
    name: "    AK-900 Wired Keyboard",
    price: 600,
    discount: 85,
    image: "/img/today_3.png",
  },
  {
    id: 15,
    name: "AK-900 Wired Keyboard",
    price: 900,
    discount: 90,
    image: "/img/today_1.png",
  },
  {
    id: 16,
    name: "IPS LCD Gaming Monitor",
    price: 800,
    discount: 95,
    image: "/img/today_3.png",
  },
  {
    id: 17,
    name: "S-Series Comfort Chair",
    price: 800,
    discount: 100,
    image: "/img/today_4.png",
  },
  {
    id: 18,
    name: "IPS LCD Gaming Monitor",
    price: 1000,
    discount: 105,
    image: "/img/today_2",
  },
];
